FROM node:20-alpine

WORKDIR /app

# Создаем временную директорию и устанавливаем права
RUN mkdir -p /tmp/voice-messages && chmod 777 /tmp/voice-messages

COPY package*.json ./
RUN npm install

# Не копируем файлы проекта, так как они будут монтироваться как том
# COPY . .

# Убедимся, что директория для миграций существует
RUN mkdir -p ./migrations

EXPOSE 3000

# Настраиваем команду для режима разработки
CMD ["npm", "run", "start:dev"]