version: '3.8'
services:
  # Бэкенд (NestJS) для разработки
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-app-dev
    ports:
      - '3000:3000'
    depends_on:
      - postgres_dev
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres_dev
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db_dev
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
    volumes:
      - .:/app
      - /app/node_modules
      - ./src/migrations:/app/migrations
    command: npm run start:dev
    env_file:
      - .env

  # Фронтенд (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend-dev
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
    depends_on:
      - app

  # БД для разработки
  postgres_dev:
    image: postgres:14
    container_name: postgres_dev
    environment:
      POSTGRES_DB: chat_db_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

volumes:
  postgres-data-dev: