version: '3.8'
services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  transcriber:
    build: ./transcriber
    container_name: transcriber-service
    ports:
      - "4001:4001"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
