version: '3.8'
services:
  app:
    build: .
    container_name: nest-app-prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres_prod
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db_prod
    depends_on:
      - postgres_prod
    env_file:
      - .env.prod

  postgres_prod:
    image: postgres:14
    container_name: postgres_prod
    environment:
      POSTGRES_DB: chat_db_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data

volumes:
  postgres-data-prod:
